# Generated by Django 4.2 on 2023-06-12 04:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abidan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(null=True, upload_to='abidan_book_cover', verbose_name='Book cover'),
        ),
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.SlugField(default='', verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.CharField(max_length=150, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_pages',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total pages'),
        ),
        migrations.AlterField(
            model_name='word',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abidan.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='word',
            name='burmese',
            field=models.CharField(max_length=100, null=True, verbose_name='Burmese'),
        ),
        migrations.AlterField(
            model_name='word',
            name='note',
            field=models.CharField(null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='word',
            name='page_number',
            field=models.IntegerField(verbose_name='Page no'),
        ),
        migrations.AlterField(
            model_name='word',
            name='roman',
            field=models.CharField(max_length=100, null=True, verbose_name='Roman'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=100, verbose_name='Word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_seq',
            field=models.CharField(max_length=100, null=True, verbose_name='Word sequence'),
        ),
    ]
