# Generated by Django 4.2 on 2023-04-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abidan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(null=True, upload_to='Book cover'),
        ),
    ]
