# Generated by Django 4.2 on 2023-04-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abidan', '0002_book_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='info',
            field=models.CharField(max_length=150),
        ),
    ]
