# Generated by Django 4.2 on 2023-04-06 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abidan', '0004_alter_book_book_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='info',
            new_name='subtitle',
        ),
    ]
