# Generated by Django 4.2 on 2023-04-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abidan', '0005_rename_info_book_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(null=True, upload_to='abidan_book_cover'),
        ),
    ]
