# Generated by Django 4.2 on 2023-04-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abidan', '0006_alter_book_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='info',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
