# Generated by Django 4.2 on 2023-04-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abidan', '0007_book_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='info',
        ),
    ]
