# Generated by Django 4.2 on 2023-04-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abidan', '0008_remove_book_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-code']},
        ),
    ]
