# Generated by Django 4.2 on 2023-04-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abidan', '0009_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['code']},
        ),
    ]
