# Generated by Django 4.2 on 2023-04-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abidan', '0011_alter_book_options_book_original_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='burmese',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='roman',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
