# Generated by Django 4.2 on 2023-04-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abidan', '0012_word_burmese_word_roman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='page_number',
            field=models.CharField(max_length=4),
        ),
    ]
