# Generated by Django 4.2 on 2023-04-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abidan', '0013_alter_word_page_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='page_number',
            field=models.CharField(max_length=50),
        ),
    ]
