# Generated by Django 4.2 on 2023-04-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abidan', '0014_alter_word_page_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='note',
            field=models.CharField(null=True),
        ),
    ]
