# Generated by Django 4.2 on 2023-04-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abidan', '0015_alter_word_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='page_number',
            field=models.IntegerField(),
        ),
    ]
