# Generated by Django 4.2 on 2023-04-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abidan', '0017_dict'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dict',
        ),
    ]
