# Generated by Django 4.2 on 2023-04-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abidan', '0019_dict'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dict',
            new_name='DictLookup',
        ),
    ]
