# Generated by Django 4.2 on 2023-04-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abidan', '0024_rename_d1_wordlookup_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordlookup',
            old_name='d2',
            new_name='terms',
        ),
    ]
