# Generated by Django 4.2 on 2023-04-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abidan', '0025_rename_d2_wordlookup_terms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordlookup',
            old_name='d3',
            new_name='construction',
        ),
    ]
