# Generated by Django 4.2 on 2023-04-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abidan', '0026_rename_d3_wordlookup_construction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordlookup',
            name='construction',
        ),
        migrations.RemoveField(
            model_name='wordlookup',
            name='terms',
        ),
    ]
