# Generated by Django 4.2 on 2023-04-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abidan', '0027_remove_wordlookup_construction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word_seq',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
