# Generated by Django 4.2 on 2023-04-10 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abidan', '0028_word_word_seq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='original_id',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(null=True, upload_to='abidan_book_cover', verbose_name='book cover'),
        ),
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.SlugField(default='', verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.CharField(max_length=150, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='word',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abidan.book', verbose_name='book'),
        ),
        migrations.AlterField(
            model_name='word',
            name='burmese',
            field=models.CharField(max_length=100, null=True, verbose_name='burmese'),
        ),
        migrations.AlterField(
            model_name='word',
            name='note',
            field=models.CharField(null=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='word',
            name='page_number',
            field=models.IntegerField(verbose_name='page no'),
        ),
        migrations.AlterField(
            model_name='word',
            name='roman',
            field=models.CharField(max_length=100, null=True, verbose_name='roman'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=100, verbose_name='word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_seq',
            field=models.CharField(max_length=100, null=True, verbose_name='word sequence'),
        ),
    ]
