# Generated by Django 4.2 on 2023-04-15 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abidan', '0029_remove_book_original_id_alter_book_book_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_pages',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='total pages'),
        ),
    ]
