# Generated by Django 4.2 on 2023-05-05 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='sequence')),
                ('title', models.CharField(max_length=80, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Linga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='sequence')),
                ('code', models.CharField(max_length=5, verbose_name='code')),
                ('title', models.CharField(max_length=80, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='NamaSaddamala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='title')),
                ('title_order', models.CharField(max_length=80, verbose_name='title order')),
                ('nom_sg', models.CharField(max_length=225, null=True, verbose_name='Paṭhamā Ekavacana')),
                ('nom_pl', models.CharField(max_length=225, null=True, verbose_name='Paṭhamā Bahuvacana')),
                ('voc_sl', models.CharField(max_length=225, null=True, verbose_name='Ālapana Ekavacana')),
                ('voc_pl', models.CharField(max_length=225, null=True, verbose_name='Ālapana Bahuvacana')),
                ('acc_sg', models.CharField(max_length=225, null=True, verbose_name='Dutiyā Ekavacana')),
                ('acc_pl', models.CharField(max_length=225, null=True, verbose_name='Dutiyā bahuvacana')),
                ('instr_sg', models.CharField(max_length=225, null=True, verbose_name='Tatiyā Ekavacana')),
                ('instr_pl', models.CharField(max_length=225, null=True, verbose_name='Tatiyā Bahuvacana')),
                ('dat_sg', models.CharField(max_length=225, null=True, verbose_name='Catutthī Ekavacana')),
                ('dat_pl', models.CharField(max_length=225, null=True, verbose_name='Catutthī Bahuvacana')),
                ('abl_sl', models.CharField(max_length=225, null=True, verbose_name='Pañcamī Ekavacana')),
                ('abl_pl', models.CharField(max_length=225, null=True, verbose_name='Pañcamī Bahuvacana')),
                ('gen_sl', models.CharField(max_length=225, null=True, verbose_name='Chaṭṭhī Ekavacana')),
                ('gen_pl', models.CharField(max_length=225, null=True, verbose_name='Chaṭṭhī Bahuvacana')),
                ('loc_sl', models.CharField(max_length=225, null=True, verbose_name='Sattamī Ekavacana')),
                ('loc_pl', models.CharField(max_length=225, null=True, verbose_name='Sattamī Bahuvacana')),
                ('karanta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='padanukkama.karanta', verbose_name='Kāranta')),
                ('linga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='padanukkama.linga', verbose_name='Liṅga')),
            ],
        ),
    ]
