# Generated by Django 4.2 on 2023-06-20 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_editorjs.fields
import mptt.fields
import smart_selects.db_fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipitaka', '0002_alter_commonreference_structure_alter_edition_code_and_more'),
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Karanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='Sequence')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='Linga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='Sequence')),
                ('code', models.CharField(max_length=5, verbose_name='Code')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='NamaSaddamala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('title_order', models.CharField(max_length=80, verbose_name='Title order')),
                ('title_code', models.CharField(max_length=80, verbose_name='Code')),
                ('nom_sg', models.CharField(blank=True, max_length=225, null=True, verbose_name='Paṭhamā Ekavacana')),
                ('nom_pl', models.CharField(blank=True, max_length=225, null=True, verbose_name='Paṭhamā Bahuvacana')),
                ('voc_sg', models.CharField(blank=True, max_length=225, null=True, verbose_name='Ālapana Ekavacana')),
                ('voc_pl', models.CharField(blank=True, max_length=225, null=True, verbose_name='Ālapana Bahuvacana')),
                ('acc_sg', models.CharField(blank=True, max_length=225, null=True, verbose_name='Dutiyā Ekavacana')),
                ('acc_pl', models.CharField(blank=True, max_length=225, null=True, verbose_name='Dutiyā Bahuvacana')),
                ('instr_sg', models.CharField(blank=True, max_length=225, null=True, verbose_name='Tatiyā Ekavacana')),
                ('instr_pl', models.CharField(blank=True, max_length=225, null=True, verbose_name='Tatiyā Bahuvacana')),
                ('dat_sg', models.CharField(blank=True, max_length=225, null=True, verbose_name='Catutthī Ekavacana')),
                ('dat_pl', models.CharField(blank=True, max_length=225, null=True, verbose_name='Catutthī Bahuvacana')),
                ('abl_sg', models.CharField(blank=True, max_length=225, null=True, verbose_name='Pañcamī Ekavacana')),
                ('abl_pl', models.CharField(blank=True, max_length=225, null=True, verbose_name='Pañcamī Bahuvacana')),
                ('gen_sg', models.CharField(blank=True, max_length=225, null=True, verbose_name='Chaṭṭhī Ekavacana')),
                ('gen_pl', models.CharField(blank=True, max_length=225, null=True, verbose_name='Chaṭṭhī Bahuvacana')),
                ('loc_sg', models.CharField(blank=True, max_length=225, null=True, verbose_name='Sattamī Ekavacana')),
                ('loc_pl', models.CharField(blank=True, max_length=225, null=True, verbose_name='Sattamī Bahuvacana')),
                ('popularity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Popularity')),
                ('karanta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='padanukkama.karanta', verbose_name='Kāranta')),
                ('linga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='padanukkama.linga', verbose_name='Liṅga')),
            ],
        ),
        migrations.CreateModel(
            name='NamaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='Sequence')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Padanukkama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('publication', models.BooleanField(default=False, verbose_name='Publication')),
                ('collaborators', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Collaborators')),
                ('structure', smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='table_of_content', chained_model_field='table_of_content', to='tipitaka.structure', verbose_name='Structure')),
                ('table_of_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tipitaka.tableofcontent', verbose_name='Table of Contents')),
                ('target_languages', models.ManyToManyField(to='padanukkama.language', verbose_name='Target Languages')),
                ('wordlist_version', models.ManyToManyField(to='tipitaka.wordlistversion', verbose_name='Wordlist Version')),
            ],
        ),
        migrations.CreateModel(
            name='Sadda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sadda', models.CharField(max_length=150, verbose_name='Sadda')),
                ('sadda_seq', models.CharField(default='', max_length=150, verbose_name='Pada sequence')),
                ('sadda_type', models.CharField(blank=True, choices=[('Nama', 'Nāma'), ('Akhyata', 'Akhyāta')], max_length=50, null=True, verbose_name='Type')),
                ('construction', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Construction')),
                ('description', django_editorjs.fields.EditorJsField(blank=True, null=True, verbose_name='Description')),
                ('meaning', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Meaning')),
                ('namasaddamala', models.ManyToManyField(related_name='saddas', to='padanukkama.namasaddamala', verbose_name='NamaSaddamala')),
                ('padanukkama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saddas', to='padanukkama.padanukkama', verbose_name='Padanukkama')),
            ],
        ),
        migrations.CreateModel(
            name='Pada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pada', models.CharField(max_length=150, verbose_name='Pada')),
                ('pada_seq', models.CharField(max_length=150, null=True, verbose_name='Pada sequence')),
                ('pada_roman_script', models.CharField(default='', max_length=150, null=True, verbose_name='Word in roman script')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('padanukkama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pada', to='padanukkama.padanukkama', verbose_name='Padanukkama')),
                ('parent', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='padanukkama.pada', verbose_name='Parent word')),
                ('sadda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pada', to='padanukkama.sadda', verbose_name='Sadda')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='namasaddamala',
            name='nama_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='padanukkama.namatype', verbose_name='Type'),
        ),
    ]
