# Generated by Django 4.2 on 2023-05-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namasaddamala',
            old_name='voc_sl',
            new_name='voc_sg',
        ),
    ]
