# Generated by Django 4.2 on 2023-05-24 09:19

from django.db import migrations
from django.db import migrations, models
from django.utils.translation import gettext_lazy as _

class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='akhyatasaddamala',
            name='popularity',
            field=models.IntegerField(default=0, verbose_name=_("Popularity")),
        ),
    ]
