# Generated by Django 4.2 on 2023-05-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pada',
            name='pada_type',
            field=models.CharField(blank=True, choices=[('NamaSaddamala', 'NamaSaddamala'), ('AkhyataSaddamala', 'AkhyataSaddamala')], max_length=50, null=True, verbose_name='Pada type'),
        ),
    ]
