# Generated by Django 4.2 on 2023-05-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0002_pada_pada_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pada',
            name='pada_type',
        ),
    ]
