# Generated by Django 4.2 on 2023-05-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0002_auto_20230523_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namasaddamala',
            old_name='abl_sl',
            new_name='abl_sg',
        ),
    ]
