# Generated by Django 4.2 on 2023-06-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0002_dhatugana_paccaya_dhatu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhatugana',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
    ]
