# Generated by Django 4.2 on 2023-05-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0003_auto_20230523_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namasaddamala',
            old_name='gen_sl',
            new_name='gen_sg',
        ),
    ]
