# Generated by Django 4.2 on 2023-05-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0003_remove_pada_pada_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sadda',
            name='akhyatasaddamala',
            field=models.ManyToManyField(to='padanukkama.akhyatasaddamala', verbose_name='Akhyatasaddamala'),
        ),
        migrations.AddField(
            model_name='sadda',
            name='namasaddamala',
            field=models.ManyToManyField(to='padanukkama.namasaddamala', verbose_name='Namasaddamala'),
        ),
        migrations.AddField(
            model_name='sadda',
            name='sadda_type',
            field=models.CharField(blank=True, choices=[('NamaSaddamala', 'NamaSaddamala'), ('AkhyataSaddamala', 'AkhyataSaddamala')], max_length=50, null=True, verbose_name='Type'),
        ),
    ]
