# Generated by Django 4.2 on 2023-06-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0003_alter_dhatugana_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhatugana',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
