# Generated by Django 4.2 on 2023-05-07 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0021_alter_commonreference_wordlist_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('padanukkama', '0004_remove_akhyatasaddamala_per_pu1_atta_pl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='Padanukkama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('publication', models.BooleanField(default=False, verbose_name='Publication')),
                ('collaborators', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Collaborators')),
                ('structure', models.ManyToManyField(blank=True, related_name='padanukkamas', to='tipitaka.structure', verbose_name='Structure')),
                ('table_of_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipitaka.tableofcontent', verbose_name='Table of Contents')),
                ('target_languages', models.ManyToManyField(to='padanukkama.language', verbose_name='Target Languages')),
            ],
        ),
        migrations.CreateModel(
            name='Pada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pada', models.CharField(max_length=255, verbose_name='Pada')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('padanukkama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pada', to='padanukkama.padanukkama', verbose_name='Padanukkama')),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='padanukkama.pada', verbose_name='Parent Words')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
