# Generated by Django 4.2 on 2023-05-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0004_auto_20230523_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namasaddamala',
            old_name='loc_sl',
            new_name='loc_sg',
        )
    ]
