# Generated by Django 4.2 on 2023-06-20 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0004_alter_dhatugana_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhatu',
            name='dhatugana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='padanukkama.dhatugana', verbose_name='Dhatugana'),
        ),
    ]
