# Generated by Django 4.2 on 2023-05-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0004_sadda_akhyatasaddamala_sadda_namasaddamala_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sadda',
            name='akhyatasaddamala',
        ),
        migrations.RemoveField(
            model_name='sadda',
            name='namasaddamala',
        ),
    ]
