# Generated by Django 4.2 on 2023-05-08 01:19

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0021_alter_commonreference_wordlist_version_and_more'),
        ('padanukkama', '0005_language_padanukkama_pada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padanukkama',
            name='structure',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='table_of_content', chained_model_field='table_of_content', related_name='padanukkamas', to='tipitaka.structure', verbose_name='Structure'),
        ),
    ]
