# Generated by Django 4.2 on 2023-06-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0005_alter_dhatu_dhatugana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paccaya',
            name='dhatugana',
        ),
        migrations.AddField(
            model_name='dhatugana',
            name='paccaya',
            field=models.ManyToManyField(to='padanukkama.paccaya', verbose_name='Paccaya'),
        ),
    ]
