# Generated by Django 4.2 on 2023-05-08 02:54

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0021_alter_commonreference_wordlist_version_and_more'),
        ('padanukkama', '0006_alter_padanukkama_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padanukkama',
            name='structure',
        ),
        migrations.AddField(
            model_name='padanukkama',
            name='structure',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='edition', chained_model_field='edition', default=1, on_delete=django.db.models.deletion.CASCADE, to='tipitaka.structure', verbose_name='structure'),
            preserve_default=False,
        ),
    ]
