# Generated by Django 4.2 on 2023-06-01 04:25

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('padanukkama', '0006_sadda_akhyatasaddamala_sadda_namasaddamala_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sadda',
            name='meaning',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Meaning'),
        ),
    ]
