# Generated by Django 4.2 on 2023-05-08 03:16

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0021_alter_commonreference_wordlist_version_and_more'),
        ('padanukkama', '0007_remove_padanukkama_structure_padanukkama_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padanukkama',
            name='structure',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='table_of_content', chained_model_field='table_of_content', on_delete=django.db.models.deletion.CASCADE, to='tipitaka.structure', verbose_name='Structure'),
        ),
    ]
