# Generated by Django 4.2 on 2023-06-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0007_alter_sadda_meaning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sadda',
            name='akhyatasaddamala',
            field=models.ManyToManyField(related_name='saddas', to='padanukkama.akhyatasaddamala', verbose_name='Akhyatasaddamala'),
        ),
        migrations.AlterField(
            model_name='sadda',
            name='namasaddamala',
            field=models.ManyToManyField(related_name='saddas', to='padanukkama.namasaddamala', verbose_name='Namasaddamala'),
        ),
    ]
