# Generated by Django 4.2 on 2023-06-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0008_alter_sadda_akhyatasaddamala_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sadda',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
