# Generated by Django 4.2 on 2023-06-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0008_historicalsadda_historicalpada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalPada',
        ),
    ]
