# Generated by Django 4.2 on 2023-06-25 06:14

from django.db import migrations
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0009_delete_historicalpada'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsadda',
            name='state',
            field=django_xworkflows.models.StateField(max_length=16, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='new', name='SaddaTranslationWorkflow', states=['new', 'translation', 'review', 'approved'])),
        ),
        migrations.AddField(
            model_name='sadda',
            name='state',
            field=django_xworkflows.models.StateField(max_length=16, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='new', name='SaddaTranslationWorkflow', states=['new', 'translation', 'review', 'approved'])),
        ),
    ]
