# Generated by Django 4.2 on 2023-05-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0021_alter_commonreference_wordlist_version_and_more'),
        ('padanukkama', '0010_padanukkama_wordlist_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padanukkama',
            name='wordlist_version',
            field=models.ManyToManyField(to='tipitaka.wordlistversion', verbose_name='Wordlist Version'),
        ),
    ]
