# Generated by Django 4.2 on 2023-06-25 13:11

from django.db import migrations
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0010_historicalsadda_state_sadda_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsadda',
            name='state',
            field=django_xworkflows.models.StateField(max_length=16, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='new', name='SaddaTranslationWorkflow', states=['new', 'translated', 'reviewed', 'approved'])),
        ),
        migrations.AlterField(
            model_name='sadda',
            name='state',
            field=django_xworkflows.models.StateField(max_length=16, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='new', name='SaddaTranslationWorkflow', states=['new', 'translated', 'reviewed', 'approved'])),
        ),
    ]
