# Generated by Django 4.2 on 2023-06-01 23:17

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0011_alter_sadda_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sadda',
            name='description',
            field=django_editorjs.fields.EditorJsField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
