# Generated by Django 4.2 on 2023-05-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0011_alter_padanukkama_wordlist_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='pada',
            name='pada_seq',
            field=models.CharField(max_length=255, null=True, verbose_name='Pada Sequence'),
        ),
    ]
