# Generated by Django 4.2 on 2023-06-28 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('padanukkama', '0011_alter_historicalsadda_state_alter_sadda_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaddaStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('sadda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_histories', to='padanukkama.sadda', verbose_name='Sadda')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
