# Generated by Django 4.2 on 2023-05-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0012_pada_pada_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='pada',
            name='pada_roman_script',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='word in roman script'),
        ),
        migrations.AlterField(
            model_name='pada',
            name='pada',
            field=models.CharField(max_length=150, verbose_name='Pada'),
        ),
        migrations.AlterField(
            model_name='pada',
            name='pada_seq',
            field=models.CharField(max_length=150, null=True, verbose_name='Pada Sequence'),
        ),
    ]
