# Generated by Django 4.2 on 2023-06-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0012_alter_sadda_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sadda',
            name='construction',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Construction'),
        ),
    ]
