# Generated by Django 4.2 on 2023-06-29 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0012_saddastatushistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaddaStatusHistory',
        ),
    ]
