# Generated by Django 4.2 on 2023-05-13 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0013_pada_pada_roman_script_alter_pada_pada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pada',
            old_name='parents',
            new_name='parent',
        ),
    ]
