# Generated by Django 4.2 on 2023-06-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0013_alter_sadda_construction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namasaddamala',
            name='title_code',
            field=models.CharField(max_length=80, verbose_name='Code'),
        ),
    ]
