# Generated by Django 4.2 on 2023-06-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0014_alter_namasaddamala_title_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akhyatasaddamala',
            name='title_code',
            field=models.CharField(max_length=80, verbose_name='Code'),
        ),
    ]
