# Generated by Django 4.2 on 2023-05-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0014_rename_parents_pada_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pada',
            name='uuid',
            field=models.CharField(max_length=10, null=True, verbose_name='UUID'),
        ),
    ]
