# Generated by Django 4.2 on 2023-06-09 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0015_alter_akhyatasaddamala_title_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pada',
            name='sadda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pada', to='padanukkama.sadda', verbose_name='Sadda'),
        ),
    ]
