# Generated by Django 4.2 on 2023-05-13 23:52

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0015_pada_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pada',
            name='parent',
        ),
        migrations.AddField(
            model_name='pada',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='padanukkama.pada', verbose_name='Parent Words'),
        ),
    ]
