# Generated by Django 4.2 on 2023-06-12 04:08

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0016_alter_pada_sadda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akhyatasaddamala',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='akhyatasaddamala',
            name='title_order',
            field=models.CharField(max_length=80, verbose_name='Title order'),
        ),
        migrations.AlterField(
            model_name='dhatu',
            name='sequence',
            field=models.IntegerField(verbose_name='Sequence'),
        ),
        migrations.AlterField(
            model_name='dhatu',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='karanta',
            name='sequence',
            field=models.IntegerField(verbose_name='Sequence'),
        ),
        migrations.AlterField(
            model_name='karanta',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='linga',
            name='code',
            field=models.CharField(max_length=5, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='linga',
            name='sequence',
            field=models.IntegerField(verbose_name='Sequence'),
        ),
        migrations.AlterField(
            model_name='linga',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='namasaddamala',
            name='acc_pl',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Dutiyā Bahuvacana'),
        ),
        migrations.AlterField(
            model_name='namatype',
            name='sequence',
            field=models.IntegerField(verbose_name='Sequence'),
        ),
        migrations.AlterField(
            model_name='namatype',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='paccaya',
            name='sequence',
            field=models.IntegerField(verbose_name='Sequence'),
        ),
        migrations.AlterField(
            model_name='paccaya',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='pada',
            name='pada_roman_script',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Word in roman script'),
        ),
        migrations.AlterField(
            model_name='pada',
            name='parent',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='padanukkama.pada', verbose_name='Parent word'),
        ),
    ]
