# Generated by Django 4.2 on 2023-05-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0016_remove_pada_parent_pada_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pada',
            name='uuid',
        ),
    ]
