# Generated by Django 4.2 on 2023-05-17 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0017_remove_pada_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='sequence')),
                ('code', models.CharField(max_length=5, verbose_name='code')),
                ('title', models.CharField(max_length=80, verbose_name='title')),
            ],
        ),
        migrations.AddField(
            model_name='karanta',
            name='code',
            field=models.CharField(default='code', max_length=5, verbose_name='code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='namasaddamala',
            name='nama_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='padanukkama.namatype', verbose_name='Type'),
        ),
    ]
