# Generated by Django 4.2 on 2023-06-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0018_remove_sadda_akhyatasaddamala_alter_sadda_sadda_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sadda',
            name='sadda_type',
            field=models.CharField(blank=True, choices=[('Nama', 'Nāma'), ('Akhyata', 'Akhyāta')], max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.DeleteModel(
            name='AkhyataSaddamala',
        ),
        migrations.DeleteModel(
            name='Dhatu',
        ),
        migrations.DeleteModel(
            name='Paccaya',
        ),
    ]
