# Generated by Django 4.2 on 2023-05-17 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0018_namatype_karanta_code_namasaddamala_nama_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sadda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sadda', models.CharField(max_length=150, verbose_name='Sadda')),
                ('meaning', models.TextField(verbose_name='Meaning')),
                ('construction', models.CharField(max_length=150, verbose_name='Contraction')),
                ('sadda_type', models.CharField(choices=[('nama', 'NamaSaddamala'), ('akhyata', 'AkhyataSaddamala')], max_length=10, verbose_name='Sadda Type')),
                ('linked_sadda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_saddas', to='padanukkama.sadda', verbose_name='Linked Sadda')),
            ],
        ),
    ]
