# Generated by Django 4.2 on 2023-06-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0019_alter_sadda_sadda_type_delete_akhyatasaddamala_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paccaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('title_order', models.CharField(max_length=80, verbose_name='Title order')),
            ],
        ),
        migrations.AlterField(
            model_name='sadda',
            name='namasaddamala',
            field=models.ManyToManyField(related_name='saddas', to='padanukkama.namasaddamala', verbose_name='NamaSaddamala'),
        ),
        migrations.CreateModel(
            name='Dhatu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('title_order', models.CharField(max_length=80, verbose_name='Title order')),
                ('definition', models.CharField(max_length=80, verbose_name='Definition')),
                ('meaning', models.CharField(max_length=80, verbose_name='Meaning')),
                ('popularity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Popularity')),
                ('paccaya', models.ManyToManyField(related_name='dhatus', to='padanukkama.paccaya', verbose_name='Paccaya')),
            ],
        ),
    ]
