# Generated by Django 4.2 on 2023-05-17 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0019_sadda'),
    ]

    operations = [
        migrations.AddField(
            model_name='sadda',
            name='padanukkama',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saddas', to='padanukkama.padanukkama', verbose_name='Padanukkama'),
            preserve_default=False,
        ),
    ]
