# Generated by Django 4.2 on 2023-05-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0020_sadda_padanukkama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sadda',
            name='sadda_type',
            field=models.CharField(choices=[('NamaSaddamala', 'NamaSaddamala'), ('AkhyataSaddamala', 'AkhyataSaddamala')], max_length=20, verbose_name='Sadda Type'),
        ),
    ]
