# Generated by Django 4.2 on 2023-06-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0020_paccaya_alter_sadda_namasaddamala_dhatu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhatu',
            name='title_order',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Title order'),
        ),
        migrations.AlterField(
            model_name='paccaya',
            name='title_order',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Title order'),
        ),
    ]
