# Generated by Django 4.2 on 2023-05-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0021_alter_sadda_sadda_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sadda',
            name='sadda_seq',
            field=models.CharField(default='', max_length=150, verbose_name='Pada sequence'),
        ),
    ]
