# Generated by Django 4.2 on 2023-05-19 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0022_sadda_sadda_seq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karanta',
            name='code',
        ),
        migrations.RemoveField(
            model_name='namatype',
            name='code',
        ),
    ]
