# Generated by Django 4.2 on 2023-06-20 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0022_dhatugana_remove_dhatu_paccaya_dhatu_dhatugana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhatu',
            name='dhatugana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='padanukkama.dhatugana', verbose_name='Dhatugana'),
        ),
    ]
