# Generated by Django 4.2 on 2023-05-20 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0023_remove_karanta_code_remove_namatype_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sadda',
            name='linked_sadda',
        ),
        migrations.RemoveField(
            model_name='sadda',
            name='sadda_type',
        ),
        migrations.AddField(
            model_name='pada',
            name='linked_sadda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_saddas', to='padanukkama.pada', verbose_name='Linked Sadda'),
        ),
        migrations.AddField(
            model_name='pada',
            name='sadda_type',
            field=models.CharField(choices=[('NamaSaddamala', 'NamaSaddamala'), ('AkhyataSaddamala', 'AkhyataSaddamala')], default=0, max_length=20, verbose_name='Sadda Type'),
            preserve_default=False,
        ),
    ]
