# Generated by Django 4.2 on 2023-05-21 14:13

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0024_remove_sadda_linked_sadda_remove_sadda_sadda_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pada',
            name='sadda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='padanukkama.sadda', verbose_name='Sadda'),
        ),
        migrations.AlterField(
            model_name='pada',
            name='linked_sadda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_saddas', to='padanukkama.pada', verbose_name='Linked Sadda'),
        ),
        migrations.AlterField(
            model_name='pada',
            name='parent',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='padanukkama.pada', verbose_name='Parent Words'),
        ),
        migrations.AlterField(
            model_name='pada',
            name='sadda_type',
            field=models.CharField(choices=[('NamaSaddamala', 'NamaSaddamala'), ('AkhyataSaddamala', 'AkhyataSaddamala')], max_length=20, null=True, verbose_name='Sadda Type'),
        ),
    ]
