# Generated by Django 4.2 on 2023-05-22 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padanukkama', '0025_pada_sadda_alter_pada_linked_sadda_alter_pada_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pada',
            old_name='sadda_type',
            new_name='pada_type',
        ),
        migrations.RemoveField(
            model_name='pada',
            name='linked_sadda',
        ),
    ]
