# Generated by Django 4.2 on 2023-04-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=5, verbose_name='code')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='description')),
            ],
        ),
    ]
