# Generated by Django 4.2 on 2023-05-24 16:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=5, verbose_name='code')),
                ('title', models.CharField(db_index=True, max_length=80, verbose_name='title')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('digitization', models.BooleanField(default=False, verbose_name='Digitization')),
                ('version', models.CharField(blank=True, max_length=10, verbose_name='version')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(db_index=True, verbose_name='Page Number')),
                ('content', models.TextField(null=True, verbose_name='Content')),
                ('proofread', models.BooleanField(default=False, verbose_name='Proof-read')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipitaka.edition', verbose_name='Edition')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='code')),
                ('description', models.CharField(blank=True, max_length=80, verbose_name='description')),
                ('flag', models.ImageField(blank=True, upload_to='script', verbose_name='Flag')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_number', models.IntegerField(db_index=True, verbose_name='number')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('total_pages', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='total pages')),
                ('book_cover', models.ImageField(blank=True, null=True, upload_to='tipitaka_book_cover', verbose_name='book cover')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipitaka.edition', verbose_name='edition')),
            ],
            options={
                'ordering': ['volume_number'],
            },
        ),
        migrations.CreateModel(
            name='WordlistVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0, verbose_name='version')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipitaka.edition', verbose_name='edition')),
            ],
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(default='', max_length=20, verbose_name='code')),
                ('word', models.CharField(default='', max_length=150, verbose_name='word')),
                ('word_seq', models.CharField(default='', max_length=150, verbose_name='word sequence')),
                ('word_roman_script', models.CharField(default='', max_length=150, null=True, verbose_name='word in roman script')),
                ('position', models.IntegerField(default=0, verbose_name='position')),
                ('line_number', models.IntegerField(default=0, null=True, verbose_name='line no')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipitaka.edition', verbose_name='edition')),
                ('page', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='volume', chained_model_field='volume', on_delete=django.db.models.deletion.CASCADE, to='tipitaka.page', verbose_name='page')),
                ('volume', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='edition', chained_model_field='edition', on_delete=django.db.models.deletion.CASCADE, to='tipitaka.volume', verbose_name='volume')),
                ('wordlist_version', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='edition', chained_model_field='edition', on_delete=django.db.models.deletion.CASCADE, to='tipitaka.wordlistversion', verbose_name='wordlist version')),
            ],
        ),
        migrations.CreateModel(
            name='TableOfContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='code')),
                ('slug', models.SlugField(default='', unique=True)),
                ('wordlist_version', models.ManyToManyField(related_name='wordlist_version', to='tipitaka.wordlistversion', verbose_name='wordlist version')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='code')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('ro', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Roman Script')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tipitaka.structure')),
                ('table_of_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipitaka.tableofcontent', verbose_name='table of contents')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='page',
            name='volume',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='edition', chained_model_field='edition', on_delete=django.db.models.deletion.CASCADE, to='tipitaka.volume', verbose_name='Volume'),
        ),
        migrations.AddField(
            model_name='edition',
            name='script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipitaka.script', verbose_name='script'),
        ),
        migrations.CreateModel(
            name='CommonReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_position', models.CharField(max_length=20, null=True, verbose_name='From Position')),
                ('to_position', models.CharField(max_length=20, null=True, verbose_name='To Position')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Description')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipitaka.structure', verbose_name='structure')),
                ('wordlist_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipitaka.wordlistversion', verbose_name='Wordlist Version')),
            ],
        ),
    ]
