# Generated by Django 4.2 on 2023-04-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='code',
            field=models.SlugField(max_length=20, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='script',
            name='description',
            field=models.CharField(blank=True, max_length=80, verbose_name='description'),
        ),
    ]
