# Generated by Django 4.2 on 2023-04-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableofcontent',
            name='edition',
            field=models.ManyToManyField(limit_choices_to=models.Q(('version__gt', 0)), related_name='edition', to='tipitaka.edition', verbose_name='edition'),
        ),
    ]
