# Generated by Django 4.2 on 2023-04-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0002_alter_script_code_alter_script_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='flag',
            field=models.ImageField(blank=True, height_field=30, upload_to='script', verbose_name='Flag', width_field=42),
        ),
    ]
