# Generated by Django 4.2 on 2023-04-21 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0003_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
