# Generated by Django 4.2 on 2023-04-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0003_script_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='flag',
            field=models.ImageField(blank=True, height_field='30', upload_to='script', verbose_name='Flag', width_field='42'),
        ),
    ]
