# Generated by Django 4.2 on 2023-04-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0004_delete_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='code',
            field=models.CharField(db_index=True, max_length=20, null=True, unique=True, verbose_name='code'),
        ),
    ]
