# Generated by Django 4.2 on 2023-04-11 15:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0005_alter_script_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=5, verbose_name='code')),
                ('description', models.CharField(blank=True, max_length=80, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=5, verbose_name='number')),
                ('total_pages', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='total pages')),
                ('page_image', models.ImageField(null=True, upload_to='tipitaka_page', verbose_name='image')),
                ('proofread', models.BooleanField(default=False, verbose_name='Proof-read')),
            ],
        ),
        migrations.AlterField(
            model_name='script',
            name='code',
            field=models.CharField(db_index=True, max_length=20, verbose_name='code'),
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_index', models.CharField(max_length=20, verbose_name='word index')),
                ('word', models.CharField(max_length=150, verbose_name='word')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipitaka.page', verbose_name='Page')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=5, verbose_name='number')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='name')),
                ('total_pages', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='total pages')),
                ('book_cover', models.ImageField(null=True, upload_to='tipitaka_book_cover', verbose_name='book cover')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipitaka.edition', verbose_name='edition')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipitaka.volume', verbose_name='volume'),
        ),
        migrations.AddField(
            model_name='edition',
            name='script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipitaka.script', verbose_name='script'),
        ),
    ]
