# Generated by Django 4.2 on 2023-04-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0006_edition_page_alter_script_code_wordlist_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='title',
            field=models.CharField(blank=True, max_length=80, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
