# Generated by Django 4.2 on 2023-04-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0006_structure_hi_structure_km_structure_lo_structure_my_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='code',
            field=models.CharField(max_length=20, null=True, verbose_name='code'),
        ),
    ]
