# Generated by Django 4.2 on 2023-04-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0007_alter_structure_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='code'),
        ),
    ]
