# Generated by Django 4.2 on 2023-04-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0007_edition_title_alter_edition_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
    ]
