# Generated by Django 4.2 on 2023-04-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0008_alter_edition_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
