# Generated by Django 4.2 on 2023-04-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0008_alter_structure_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='hi',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Hindi Script'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='km',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Khmar Script'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='lo',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Lao Script'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='my',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Myanmar Script'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='ro',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Roman Script'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='si',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Sinhala Script'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Title'),
        ),
    ]
