# Generated by Django 4.2 on 2023-04-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0009_alter_structure_hi_alter_structure_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableofcontent',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
