# Generated by Django 4.2 on 2023-04-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0009_edition_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='archived',
        ),
        migrations.AddField(
            model_name='edition',
            name='digitization',
            field=models.BooleanField(default=False, verbose_name='Digitization'),
        ),
        migrations.AddField(
            model_name='edition',
            name='version',
            field=models.CharField(blank=True, max_length=10, verbose_name='version'),
        ),
    ]
