# Generated by Django 4.2 on 2023-04-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0010_remove_edition_archived_edition_digitization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='title',
            field=models.CharField(db_index=True, max_length=80, verbose_name='title'),
        ),
    ]
