# Generated by Django 4.2 on 2023-04-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0011_alter_edition_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
