# Generated by Django 4.2 on 2023-04-28 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0011_alter_tableofcontent_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableofcontent',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.CreateModel(
            name='CommonReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_position', models.CharField(max_length=20, null=True, verbose_name='From Position')),
                ('to_position', models.CharField(max_length=20, null=True, verbose_name='To Position')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Description')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipitaka.structure', verbose_name='structure')),
            ],
        ),
    ]
