# Generated by Django 4.2 on 2023-04-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0012_volume_description_alter_volume_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='tipitaka_book_cover', verbose_name='book cover'),
        ),
    ]
