# Generated by Django 4.2 on 2023-04-28 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0012_alter_tableofcontent_slug_commonreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonreference',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tipitaka.edition', verbose_name='edition'),
            preserve_default=False,
        ),
    ]
