# Generated by Django 4.2 on 2023-04-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0013_commonreference_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='WordList',
            name='code',
            field=models.SlugField(default='', max_length=20, verbose_name='code'),
        ),
    ]
