# Generated by Django 4.2 on 2023-04-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0013_alter_volume_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='number',
            field=models.IntegerField(db_index=True, verbose_name='number'),
        ),
    ]
