# Generated by Django 4.2 on 2023-04-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0014_alter_volume_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='total_pages',
        ),
    ]
