# Generated by Django 4.2 on 2023-04-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0014_alter_wordlist_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableofcontent',
            name='wordlist_version',
            field=models.ManyToManyField(related_name='wordlist_version', to='tipitaka.wordlistversion', verbose_name='wordlist_version'),
        ),
    ]
