# Generated by Django 4.2 on 2023-04-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0015_remove_page_total_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(null=True, verbose_name='content'),
        ),
    ]
