# Generated by Django 4.2 on 2023-04-29 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0015_tableofcontent_wordlist_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableofcontent',
            name='edition',
        ),
    ]
