# Generated by Django 4.2 on 2023-04-13 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0016_page_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page_image',
        ),
    ]
