# Generated by Django 4.2 on 2023-04-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0017_remove_page_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='number',
            field=models.IntegerField(db_index=True, verbose_name='number'),
        ),
    ]
