# Generated by Django 4.2 on 2023-04-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0017_remove_commonreference_edition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableofcontent',
            name='wordlist_version',
            field=models.ManyToManyField(related_name='wordlist_version', to='tipitaka.wordlistversion', verbose_name='wordlist version'),
        ),
    ]
