# Generated by Django 4.2 on 2023-04-13 10:51

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0018_alter_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipitaka.edition', verbose_name='edition'),
        ),
        migrations.AlterField(
            model_name='page',
            name='volume',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='edition', chained_model_field='edition', on_delete=django.db.models.deletion.CASCADE, to='tipitaka.volume', verbose_name='volume'),
        ),
    ]
