# Generated by Django 4.2 on 2023-04-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0019_page_edition_alter_page_volume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Page',
            old_name='number',
            new_name='page_number',
        ),
    ]
