# Generated by Django 4.2 on 2023-05-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0019_alter_wordlist_wordlist_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['page_number']},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ['volume_number']},
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='line_number',
            field=models.IntegerField(default=0, null=True, verbose_name='line no'),
        ),
    ]
