# Generated by Django 4.2 on 2023-05-05 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tipitaka', '0020_alter_page_options_alter_volume_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonreference',
            name='wordlist_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipitaka.wordlistversion', verbose_name='Wordlist Version'),
        ),
        migrations.AlterField(
            model_name='wordlistversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
    ]
