# Generated by Django 4.2 on 2023-04-14 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0020_auto_20230414_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipitaka.edition', verbose_name='edition'),
        ),
    ]
