# Generated by Django 4.2 on 2023-05-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0021_alter_commonreference_wordlist_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlist',
            name='word_roman_script',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='word in roman script'),
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='word_seq',
            field=models.CharField(default='', max_length=150, verbose_name='word sequence'),
        ),
    ]
