# Generated by Django 4.2 on 2023-04-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0021_alter_page_edition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Volume',
            old_name='number',
            new_name='volume_number',
        ),
    ]
