# Generated by Django 4.2 on 2023-05-12 07:58

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0022_wordlist_word_roman_script_alter_wordlist_word_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipitaka.edition', verbose_name='Edition'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_number',
            field=models.IntegerField(db_index=True, verbose_name='Page Number'),
        ),
        migrations.AlterField(
            model_name='page',
            name='volume',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='edition', chained_model_field='edition', on_delete=django.db.models.deletion.CASCADE, to='tipitaka.volume', verbose_name='Volume'),
        ),
    ]
