# Generated by Django 4.2 on 2023-04-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0022_auto_20230414_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordlist',
            name='word_index',
        ),
        migrations.AddField(
            model_name='wordlist',
            name='code',
            field=models.CharField(default='', max_length=20, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='wordlist',
            name='line_number',
            field=models.IntegerField(default=0, verbose_name='line no'),
        ),
        migrations.AddField(
            model_name='wordlist',
            name='position',
            field=models.IntegerField(default=0, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='wordlist',
            name='word_seq',
            field=models.CharField(default='', max_length=150, verbose_name='word'),
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='word',
            field=models.CharField(default='', max_length=150, verbose_name='word'),
        ),
    ]
