# Generated by Django 4.2 on 2023-04-17 04:05

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0023_remove_wordlist_word_index_wordlist_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlist',
            name='edition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tipitaka.edition', verbose_name='edition'),
        ),
        migrations.AddField(
            model_name='wordlist',
            name='volume',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='edition', chained_model_field='edition', null=True, on_delete=django.db.models.deletion.CASCADE, to='tipitaka.volume', verbose_name='volume'),
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='page',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='volume', chained_model_field='volume', null=True, on_delete=django.db.models.deletion.CASCADE, to='tipitaka.page', verbose_name='page'),
        ),
    ]
