# Generated by Django 4.2 on 2023-04-17 04:06

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0024_wordlist_edition_wordlist_volume_alter_wordlist_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlist',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipitaka.edition', verbose_name='edition'),
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='page',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='volume', chained_model_field='volume', on_delete=django.db.models.deletion.CASCADE, to='tipitaka.page', verbose_name='page'),
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='volume',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='edition', chained_model_field='edition', on_delete=django.db.models.deletion.CASCADE, to='tipitaka.volume', verbose_name='volume'),
        ),
    ]
