# Generated by Django 4.2 on 2023-04-17 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipitaka', '0026_wordlistversion_wordlist_wordlistversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlist',
            name='wordlistversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipitaka.wordlistversion', verbose_name='Wordlist version'),
        ),
    ]
