# Generated by Django 4.2 on 2023-04-17 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tipitaka', '0027_alter_wordlist_wordlistversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlistversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
    ]
